cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from shop import views

urlpatterns = [
    # Forgot password - reset
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin-products/', views.admin_page, name='admin_page'),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('django.contrib.auth.urls')),  # This handles login/logout
    path('register/', include('register.urls', namespace='register')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':
    settings.MEDIA_ROOT}), #serve media files when deployed
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':
    settings.STATIC_ROOT}), #serve static files when deployed
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),  # For creating a new order
    path('created/', views.order_created, name='order_created'),  # For confirming order creation
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),  # Admin order detail
    path('order/<int:order_id>/', views.order_detail_view, name='order_detail'),  # Order detail for users
    path('history/', views.order_history_view, name='order_history'),  # User order history
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('register/', views.register_user, name='register_user'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, 
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
    path('product/create/', views.ProductCreateView.as_view(),
         name='product_create'),
    path('product/delete/<int:pk>/', views.ProductDeleteView.as_view(),
         name='product_delete'),
    path('product/edit/<int:pk>/', views.ProductUpdateView.as_view(),
         name='product_edit'),
    path('admin-products/', views.admin_page, name='admin_page'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
class CartAddProductForm(forms.Form):
    def __init__(self, *args, **kwargs):
        try: #if choices for quantity drop-down provided
            mychoices = kwargs.pop('my_choices')
            super(CartAddProductForm, self).__init__(*args, **kwargs)
            self.fields["quantity"] = forms.TypedChoiceField(choices=mychoices,
                coerce=int)
        except: #use default of 21 if choices not provided
            super(CartAddProductForm, self).__init__(*args, **kwargs)
            self.fields["quantity"] = forms.TypedChoiceField(choices=[(i, str(i)) for i in range(1, 21)],
                                                             coerce=int)

    update = forms.BooleanField(required=False,
                                    initial=False,
                                    widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        product = get_object_or_404(Product, id=item['product'].id)
        # limit the 'update' quantity choices based on quantity in inventory
        choices = [(i, str(i)) for i in range(1, product.quantity + 1)]

        item['update_quantity_form'] = CartAddProductForm(
            my_choices=choices,
            initial={'quantity': item['quantity'],
                     'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Your Shopping Cart
{% endblock %}

{% block content %}
  <h1>Your Shopping Cart</h1>
  
  {% if user.is_authenticated %}
    <table class="cart">
      <thead>
        <tr>
          <th>Image</th>
          <th>Product</th>
          <th>Quantity</th>
          <th>Remove</th>
          <th>Unit Price</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        {% for item in cart %}
          {% with product=item.product %}
            <tr>
              <td>
                <a href="{{ product.get_absolute_url }}">
                  <img class ="cart-image" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                </a>
              </td>
              <td>{{ product.name }}</td>
              <td>
                <form action="{% url "cart:cart_add" product.id %}" method="post">
                  {{ item.update_quantity_form.quantity }}
                  {{ item.update_quantity_form.update }}
                  <input type="submit" value="Update">
                  {% csrf_token %}
                </form>
              </td>
              <td><a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
              <td class="num">${{ item.price }}</td>
              <td class="num">${{ item.total_price }}</td>
            </tr>
          {% endwith %}
        {% endfor %}
        <tr class="total">
          <td>Total</td>
          <td colspan="4"></td>
          <td class="num">${{ cart.get_total_price }}</td>
        </tr>
      </tbody>
    </table>
    <p class="text-right">
      <a href="{% url "shop:product_list" %}" class="button light">Continue Shopping</a>
      <a href="{% url "orders:order_create" %}" class="button">
        Checkout
      </a>
    </p>
  {% else %}
    <p>You need to log in to view your cart. <a href="{% url 'login' %}">Click here to login</a> or <a href="{% url 'register:register_user' %}">create an account</a>.</p>
  {% endif %}
{% endblock %}