cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from shop import views

urlpatterns = [
    # Forgot password - reset
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin-products/', views.admin_page, name='admin_page'),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('django.contrib.auth.urls')),  # This handles login/logout
    path('register/', include('register.urls', namespace='register')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':
    settings.MEDIA_ROOT}), #serve media files when deployed
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':
    settings.STATIC_ROOT}), #serve static files when deployed
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),  # For creating a new order
    path('created/', views.order_created, name='order_created'),  # For confirming order creation
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),  # Admin order detail
    path('order/<int:order_id>/', views.order_detail_view, name='order_detail'),  # Order detail for users
    path('history/', views.order_history_view, name='order_history'),  # User order history
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('register/', views.register_user, name='register_user'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, 
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
    path('product/create/', views.ProductCreateView.as_view(),
         name='product_create'),
    path('product/delete/<int:pk>/', views.ProductDeleteView.as_view(),
         name='product_delete'),
    path('product/edit/<int:pk>/', views.ProductUpdateView.as_view(),
         name='product_edit'),
    path('admin-products/', views.admin_page, name='admin_page'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    quantity = models.IntegerField(default=2)

    class Meta:
        ordering = ('name',)
        indexes = [
            models.Index(fields=['id', 'slug'], name='product_id_slug_idx')  # Add name attribute here
        ]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[str(self.id), self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product  # Import Category and Product
from cart.forms import CartAddProductForm
from cart.cart import Cart
from orders.models import Order  # Import Order from orders.models
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import user_passes_test  # Import for admin check
from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic.edit import DeleteView



@user_passes_test(lambda u: u.is_superuser)  # Ensure only superusers can access this page
def admin_page(request):
    products = Product.objects.all()  # Fetch all products for display
    return render(request, 'shop/admin.html', {'products': products})

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    cart = Cart(request)
    return render(request,
                  'shop/product/product_list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products,
                   'cart': cart})

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    # Set choices for quantity available based on inventory and items in this session's cart
    cart = Cart(request)
    cartquantity = 0
    # If item in cart, subtract the items in the cart from the quantity available
    for item in cart:
        cartproduct = get_object_or_404(Product, id=item['product'].id)
        if product == cartproduct:
            cartquantity = item['quantity']
            break
    if product.quantity - cartquantity > 0:
        choices = [(i, str(i)) for i in range(1, product.quantity - cartquantity + 1)]
    else:  # No items left in inventory for this session
        choices = [(1, 0)]

    cart_product_form = CartAddProductForm(my_choices=choices)
    return render(request,
                  'shop/product/product_detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'cart': cart})

# View for showing all orders for a logged-in user
def order_history_view(request):
    if request.user.is_authenticated:  # Check if user is authenticated
        orders = Order.objects.filter(user=request.user)  # Use user instead of customer
    else:
        orders = []  # Return an empty list if not authenticated
    return render(request, 'shop/order_history.html', {'orders': orders})

# View for showing details of a specific order
def order_detail_view(request, order_id):
    order = get_object_or_404(Order, id=order_id, user=request.user)  # Ensure to use user
    return render(request, 'shop/order_detail.html', {'order': order})

class ProductCreateView(CreateView):
    model = Product
    fields = ['name', 'description', 'category', 'image', 'price', 'quantity']
    template_name = 'shop/product_form.html'
    success_url = reverse_lazy('shop:product_list')

class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name', 'description', 'category', 'image', 'price', 'quantity']
    template_name = 'shop/product_edit.html'
    success_url = reverse_lazy('shop:admin_page')

class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'shop/product_delete.html'
    success_url = reverse_lazy('shop:admin_page')

shop/templates/shop/admin.html
{% extends "shop/base.html" %}

{% block title %}
    Admin
{% endblock %}

{% block content %}
<style>
    table th {
        color: black;
    }
</style>

<div class="container">
    <h2 class="text-center my-4">Admin</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Product</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
                <th scope="col">Edit</th>
                <th scope="col">Remove</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.quantity }}</td>
                <td>${{ product.price }}</td>
                <td>
                    <a href="{% url 'shop:product_edit' product.id %}" class="btn btn-secondary">Edit</a>
                </td>

                {% if product.quantity >= 1 %}
                <td><button class="btn btn-danger btn-sm" disabled>Cannot delete - Product exists</button></td>
                {% else %}
                <td>
                    <a href="{% url 'shop:product_delete' product.id %}" class="btn btn-danger btn-sm">Delete</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="text-end">
        <a href="{% url 'shop:product_create' %}" class="btn btn-primary">Add</a>
    </div>
</div>
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang ="en">
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My Shop{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-success">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Leaf It to Us</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "shop:product_list" %}">Home</a>
                </li>
                <li>
                    {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            <a class="nav-link" href="{% url "cart:cart_detail" %}">
                                Cart: {{ total_items }} item{{ total_items|pluralize }}
                            </a>
                        {% else %}
                            <a class="nav-link" href="{% url "cart:cart_detail" %}">Cart</a>
                        {% endif %}
                    {% endwith %}
                </li>
                <li>
                    {% if user.is_authenticated %}
                        <div>
                            <a class="nav-link" href="{% url 'orders:order_history' %}">Order History</a>  
                        </div>
                        {% if user.is_superuser %}
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Admin Function
                    </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'shop:admin_page' %}">Admin Product View</a></li>
                        </ul>
                    </li>
                {% endif %}
                    {% else %}
                        <div class="container">
                            <a class="nav-link" href="{% url 'orders:order_history' %}">Order History</a>  
                        </div>
                    {% endif %}

                </li>
            </ul>
        </div>
        <ul class="nav navbar-nav ml-auto">
        {% if user.is_authenticated %}
           <li>
              <form action="{% url 'logout' %}" method="post">
                 {% csrf_token %}
                 <button type="submit">Log out</button>
              </form>

           </li>
        {% else %}
            <li><a class="nav-link" href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a>
            </li>
            <li><a class="nav-link" href="{% url "register:register_user" %}"><span class="glyphicon glyphicon-log-in"></span>Sign Up</a>
            </li>

        {% endif %}
    </ul>

    </div>
</nav>


<div id="header">
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/shop/product_delete.html
{% extends "shop/base.html" %}

{% block title %}
    Confirm Delete
{% endblock %}

{% block content %}
<div class="container">
    <h2>Are you sure you want to delete "{{ object.name }}"?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, Delete</button>
        <a href="{% url 'shop:admin_page' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

shop/templates/shop/product_edit.html
{% extends "shop/base.html" %}

{% block content %}
<h2>Edit Product</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Changes</button>
</form>
{% endblock %}

shop/templates/shop/product_form.html
{% extends "shop/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Add a New Product
{% endblock %}

{% block content %}
    {% if perms.shop.add_product %}
        <form method="post" enctype="multipart/form-data" class="product-form">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Add Product</button>
            <a href="{% url 'shop:admin_page' %}" class="btn btn-secondary">Cancel</a>
        </form>
    {% else %}
        <p>You do not have permission to add a product.</p>
        <a href="{% url 'index' %}">Home</a>
    {% endif %}
{% endblock %}